// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $actiune from "./routes/actiune.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $despre from "./routes/despre.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $potential from "./routes/potential.tsx";
import * as $riscuri from "./routes/riscuri.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $RiskWheel from "./islands/RiskWheel.tsx";
import * as $ScrollAnimation from "./islands/ScrollAnimation.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/actiune.tsx": $actiune,
    "./routes/api/joke.ts": $api_joke,
    "./routes/despre.tsx": $despre,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/potential.tsx": $potential,
    "./routes/riscuri.tsx": $riscuri,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/RiskWheel.tsx": $RiskWheel,
    "./islands/ScrollAnimation.tsx": $ScrollAnimation,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
